// client_old/src/app/components/views/transactions/transactions.component.ts
import { Component, OnInit } from '@angular/core';
import { loadFromSessionStorage } from "../../../store";
import {ActivatedRoute, Router} from "@angular/router";
import { User } from "../../../types/User";
import {Transaction} from "../../../types/Transaction";
import {ApiService} from "../../../model/Api.service";
import fileDownload from "js-file-download";
import {ToastService} from "angular-toastify";

@Component({
  selector: 'app-transactions',
  templateUrl: './transactions.component.html',
  styleUrls: ['./transactions.component.scss']
})
export class TransactionsComponent implements OnInit {
  public loaded: boolean = false;
  public user?: User;

  private userToken = loadFromSessionStorage()?.acessToken;

  public transactions?: Transaction[];

  constructor(private route: ActivatedRoute, private router: Router, private _toastService: ToastService) { }

  ngOnInit(): void {
    if (!this.userToken) {
      this.router.navigate(['/']).then();
    }

    Promise.all([this.loadUser(), this.loadTransactions()]).finally(() => this.loaded = true)
  }

  async loadUser(){
    await this.route.data.subscribe(
      async (data) => {
        this.user = await data.user;
      }
    );
  }

  async loadTransactions(){
    this.transactions = await ApiService.getTransactionsFromUserID();
  }

  async download(transaction: Transaction){
    ApiService.getTransactionPdf(transaction.transactionsId)
      .then((data: any) => {
        const blob = new Blob([data], { type: "application/pdf" });
        fileDownload(blob, `facture-${transaction.transactionsId}.pdf`);
      })
      .catch(() => this._toastService.error('Oups ! Il y a une erreur veuillez réessayer ultérieurement'));
  }
}

<div *ngIf="!loaded">
  <app-loading></app-loading>
</div>

<app-header *ngIf="loaded" [user]='user'></app-header>

<main *ngIf="loaded">
  <div class="card transactions">
    <h1 class="card__title transactions__title">Mes factures</h1>

    <div *ngIf="transactions?.length" class="transactions__container">
      <div class="transaction" *ngFor="let transaction of transactions">
        <p class="transaction__id">Facture n°{{ transaction.transactionsId }}</p>
        <p class="transaction__date">{{ transaction.date }}</p>
        <div class="transaction__price">
          <span>{{ transaction.price }}</span>
          <svg *ngIf="transaction.currency === 'gem'" class="transaction__gem" width='24' height='24' viewBox='0 0 24 24'>
            <path fill='currentColor'
              d='M12 2C6.47 2 2 6.5 2 12C2 17.5 6.5 22 12 22S22 17.5 22 12 17.5 2 12 2M12 20C7.58 20 4 16.42 4 12C4 7.58 7.58 4 12 4S20 7.58 20 12C20 16.42 16.42 20 12 20M8 14L7 8L10 10L12 7L14 10L17 8L16 14H8M8.56 16C8.22 16 8 15.78 8 15.44V15H16V15.44C16 15.78 15.78 16 15.44 16H8.56Z' />
          </svg>
          <span *ngIf="transaction.currency !== 'gem'">G</span>
        </div>


        <mat-icon class="transaction__icon" (click)="download(transaction)">cloud_download</mat-icon>
      </div>
    </div>
    <p *ngIf="!transactions?.length" class="transactions__empty">Vous n'avez pas de factures</p>
  </div>
</main>

<app-footer *ngIf="loaded"></app-footer>

// client/src/components/views/transactions/transactions.tsx
import fileDownload from 'js-file-download';
import { FunctionComponent, useEffect, useState } from 'react';
import { AiOutlineCloudDownload } from 'react-icons/ai';

import { useRedirect } from '../../../hooks/useRedirect';
import { useToastify } from '../../../hooks/useToastify';
import { TransactionsService } from '../../../models/resources/transactions/transactions.service';
import { Colors } from '../../../types/enums/Colors';
import { Currencies } from '../../../types/enums/Currencies';
import { Warnings } from '../../../types/enums/Warnings';
import { Profile } from '../../../types/model/Profile';
import { Transaction as TransactionModel } from '../../../types/model/Transaction';
import { Gem } from '../../elements/gem/gem';
import { Loading } from '../../modules/loading/loading';

import style from './transactions.module.scss';

interface Props {
  profile?: Profile;
}

const Transactions: FunctionComponent<Props> = ({ profile }) => {
  const { toastError } = useToastify();
  const { warningRedirect } = useRedirect();

  const [transactions, setTransactions] = useState<TransactionModel[]>();
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const getTransactions = async () => {
      try {
        const res = await TransactionsService.getAllTransactionsFromUser();
        setTransactions(res);
      } catch (e) {
        toastError();
      }
    };

    if (!profile) {
      warningRedirect('/', Warnings.NEED_TO_LOGIN);
    }

    Promise.all([getTransactions()]).finally(() => setLoaded(true));
  }, [loaded]);

  const downloadPdf = async (transactionId: string) => {
    const data: any = await TransactionsService.getTransactionPdf(transactionId);

    const blob = new Blob([data], { type: 'application/pdf' });

    fileDownload(blob, `facture-${transactionId}.pdf`);
  };

  if (!loaded) {
    return <Loading />;
  }

  return (
    <>
      {transactions && (
        <main className={style.main}>
          <div className={style.transactions}>
            <h1 className={style.transaction__title}>Mes factures</h1>

            <div className={style.transactions__container}>
              {transactions.length ? (
                transactions.map((transaction: TransactionModel) => (
                  <div className={style.transaction}>
                    <p className={style.transaction__id}>Facture n°{transaction.transactionsId}</p>
                    <p className={style.transaction__date}>{transaction.date}</p>
                    <div className={style.transaction__price}>
                      <span>{transaction.price}</span>
                      {transaction.currency === Currencies.gem ? (
                        <Gem className={style.transaction__gem} color={Colors.black} />
                      ) : (
                        <span>€</span>
                      )}
                    </div>

                    <AiOutlineCloudDownload
                      className={style.transaction__icon}
                      onClick={() => downloadPdf(transaction.transactionsId)}
                    />
                  </div>
                ))
              ) : (
                <p className={style.transactions__empty}>Vous n'avez pas de factures</p>
              )}
            </div>
          </div>
        </main>
      )}
    </>
  );
};

export { Transactions };
